SELECT * FROM TEACHER;
SELECT * FROM LECTURE;
SELECT * FROM STUDENT;
SELECT * FROM ENROLLMENT;


-- 1.강의별 수강생 수 구하기
SELECT TITLE,INDEX_COUNT FROM LECTURE
ORDER BY TITLE ASC;

-- 2. 특정 학생의 수강 내역 조회
SELECT L.TITLE, T.NAME, E.STATUS FROM LECTURE L
JOIN ENROLLMENT E ON (E.LECTURE_ID = L.LECTURE_ID)
JOIN TEACHER T ON (T.TEACHER_ID = L.TEACHER_ID)
WHERE STUDENT_ID = 1001;

-- 3. 전공별 강의 개수 집계
SELECT SUBJECT, COUNT(CATEGORY) FROM TEACHER T
JOIN LECTURE L ON (L.TEACHER_ID = T.TEACHER_ID)
GROUP BY SUBJECT
ORDER BY SUBJECT ASC;

-- 4. 평균 점수가 80점 이상인 강의만 조회
SELECT TITLE, ROUND(AVG(GRADE_SCORE),1) FROM LECTURE L
JOIN ENROLLMENT E ON (E.LECTURE_ID = L.LECTURE_ID)
HAVING AVG(GRADE_SCORE) >= 80
GROUP BY TITLE
ORDER BY AVG(GRADE_SCORE) DESC;

-- 5. 수강기록 등록 시, 강의별 수강 인원 수 자동 집계 트리거
CREATE OR REPLACE TRIGGER TRG_24
AFTER INSERT
ON ENROLLMENT
FOR EACH ROW
BEGIN
    IF(:NEW.STATUS = 'IN')
        THEN UPDATE LECTURE
            SET INDEX_COUNT = INDEX_COUNT + 1
            WHERE PCODE = :NEW.PCODE;
    ELSE
        UPDATE LECTURE
        SET INDEX_COUNT = INDEX_COUNT - 1
        WHERE PCODE = :NEW.PCODE;
    END IF;
END;
// 잘 모르겠어요 ㅠㅠ















