-- 사용자 계정 생성
CREATE USER C##INVEST IDENTIFIED BY INVEST;

-- 접속 권한 및 테이블 생성 권한 부여
GRANT CONNECT, RESOURCE TO c##INVEST;

-- 테이블스페이스 설정
ALTER USER C##INVEST DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- ADMIN 계정에서 실행
GRANT SELECT, INSERT, UPDATE, DELETE ON USERS TO C##INVEST;
GRANT SELECT, INSERT, UPDATE, DELETE ON ASSET TO C##INVEST;
GRANT SELECT, INSERT, UPDATE, DELETE ON TRADE_HISTORY TO C##INVEST;
GRANT SELECT, INSERT, UPDATE, DELETE ON PORTFOLIO TO C##INVEST;


